### ISSUE TITLE
"Error! Reference source not found" in netx duo documentation file

### ISSUE THREAD

**Issue by Eladov** [eclipse-threadx/rtos-docs#38]
from https://github.com/eclipse-threadx/rtos-docs/blob/main/rtos-docs/netx-duo/netx-duo-secure-tls/chapter3.md#tls-record-header

![image](https://github.com/user-attachments/assets/cda90b53-51bd-4497-a7a5-3b459514236a)

seems to be a missing reference in the docs

**Comment by fdesbiens** [comment]
Thank you for letting us know, @Eladov!

This has been fixed by https://github.com/eclipse-threadx/rtos-docs/commit/07e39dd7ccd5965fb82de62d3e0ee32ad1dd8bc5
