### ISSUE TITLE
exFAT section to be removed

### ISSUE THREAD

**Issue by rahmanih** [eclipse-threadx/rtos-docs#4]
Hi @wickste, @ericwol-msft 

The FileX documentation is still having the [exFAT support section](https://github.com/eclipse-threadx/rtos-docs/blob/main/rtos-docs/filex/chapter1.md#exfat-support), while it shouldn't any more.

regards
Haithem.

**Comment by wickste** [comment]
Thank you @rahmanih!

@timlt please update accordingly.

**Comment by timlt** [comment]
PR to remove exFAT:
https://github.com/eclipse-threadx/rtos-docs/pull/16

**Comment by timlt** [comment]
@rahmanih this issue is resolved, with the above merge.
