### ISSUE TITLE
NetX Crypto Chapters are Missing

### ISSUE THREAD

**Issue by ngunderson** [eclipse-threadx/rtos-docs#6]
The NetX Duo [index.md](https://github.com/eclipse-threadx/rtos-docs/blob/main/rtos-docs/netx-duo/index.md) shows a chapter for NetX Crypto. However this content and [link](https://github.com/eclipse-threadx/rtos-docs/blob/main/rtos-docs/netx/netx-crypto/chapter1.md) doesn't exist. 

This content is available on Microsoft Learn [here](https://learn.microsoft.com/en-us/azure/rtos/netx/netx-crypto/chapter1).

**Comment by timlt** [comment]
@ngunderson this issue is resolved.
